endpoint = "http://172.24.4.63/"
client_id = "16a0f3022162a555a333"
client_secret = "5680b31608e350b52d250e7aebbb5a27af0e50e3"
certificate = """-----BEGIN CERTIFICATE-----
MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MTIwNTA5NTgzM1oXDTQ0
MTIwNTA5NTgzM1owKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDmM/Qj5v33slmH
HIHXZInLykWnHP2QmIylML76DiZenqR1M7r2jjRzxaAFz6cDVV2O14eVJI6jjfTd
SlrVwYaV6pmPDbn81YDX3NuM0ILmPU9SK1C3otYfsQ6oNf+r4CLLU3j72NfafMF5
e45mobiqj2DFWZ594sAMDFxs718EeU+nHjGUneXRXiowbR8b/83abLdVvcvMvUNj
zCe74FWms1V5MuYzo65611N8ddrZROdhYCil/mGZHw0gMmgPTGxsZ33OHoEqvcNF
Bj+Sqggd/f2pYqJAOk1HHRsbT4NoGkfBCsrtOvGL+2seeZMbYoouAoe1lSh3R2Cd
QGVm4ZEQyi3MAUFX4Ph49RTHDJuffGggj6bd81cEQz/R0ItqJNkoIXtaL9Gh3AOn
imfQe2bNJ/SMf769/9XZ3qU/EB/nqTVKqmnFluK4x4WDEpiB5hrXpSGAf8IikDUB
UdoRNSTHKrffi+3CgcVwcby7z0RD7a2mouKl5LPcYxfbozibVZsfax/zcUKHNEgp
42EUn2Izb5j77GNaGJ4s6SXwP6CcXRMDPa1JSQTMf4hq6tpOD3mCiwMCgUXphJRV
W27S6gfMLlNoIOo9L3Hy1AHhKVaKF+bdyWbnKesgCsi5IKTu7BvUUxoRArS8Ak56
JMwarocs6H2T+mZEw0TqqAfYLeeO9QIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
CSqGSIb3DQEBCwUAA4ICAQBjA6cvDG7aNw8vEPrK/Ubq6S8+UqLQRntPO8QR3U6a
y1HTjPGJ2eFHH1XvdZDgxUyQTPLm5pNvp3RkCYE5riY0iaHQCsLymYw8adUppA6G
Tjhth88JgQy8+TGwKPs8uTegL0oK3vrbYaMFfdweQGnurLPMat3Q2NCxqD7r3KFH
xvx1ubBEI9i9j8x1+TcmEWqUWx7xjsaJM24/sj6JofEoBgpjAdJDQk5867jjSo9U
/O7YPhiPrheMq3nWgppGSwKo+bhATwADZkkR1O4F5TR3+9uExQzLWYwhET1lXizd
08uxY/qB21EB4wLlde1thohko6jCf7JZUt6aMAoScaCbnogI/GFgiGo3QU2M086R
w8FLz+YVcS/I8bbQS9+V9xneQ5pvMsGoIvWfmc3HxUMDfNFUmOgWxvifjtJjPacy
MLOU1MoInN7LeDf7zj7A0V9wb0JdiMkpH1tbwimzXXdUKN+Yk8Q8BiJuCXLBov3I
nWMRzgdPQiIyHwrgcS+dNWvswK7BKGICuZlPfQ2ZHK7nc5NkpBAD9wBoeGv7eemJ
15wXPtOujWvh2P4nPLjR/03Ymu9UygZ1f0youpQpeUfhTXP5iDDiarxsC2khm3sD
wTFvhVxwPP3f1kpOuyz9GvB13V38ImumO95+d4KQOGr1KtggFWMWfJCSoCG4s5TW
8A==
-----END CERTIFICATE-----"""
org_name = "modern-libre-dev-group"