endpoint = "http://172.24.4.42/"
client_id = "636d3b65c0c7ce76e32d"
client_secret = "44085702fb2cdfd5aa79af0d19b62f536a642529"
certificate = """-----BEGIN CERTIFICATE-----
MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MTIwMTEyMDA0MVoXDTQ0
MTIwMTEyMDA0MVowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDejWr7SQzvOET3
z5TBOcPdgFrr34X1SvyPy8Ko6a8kr6ZZsPGPcYkGeMRpOCiGmTwmFFunN3swF+NP
LIw+/ph1YDIzGq0qNxmGP/p1yT1c08UKDYr8HM/W16BvkuFztL5J/A3W/ApETJci
gBoTd/3h2KS38PwKcrR/tvL0PTziaKNz0MuwLhA7Q/g3Cd7gjakJTyTr+jQ/yjge
auTUIP0sqGCQNuM2T8g2bX3kgsDSeYFNt9dgWNAnOdgYRBNs4QYaDkNIljKtzukD
A3E3NEyjTAA3nfxzb33zVmEWvlPpJp7boBMI4N8dsY6HdrYBoRs36C4unDuZzgc0
siv1wA02Y8YQPFsFByUFxvpAG8W3DE5+ZUl/M8XiTwli2yf3uI1NGblnNRjEeloM
Z91lJ/qXrQYn1eQpasVE0V+cJarmMTVBAW3obOZFtWrM0al0gj0SGDRIiNmfvPfW
EDBDt8ot5F0lIIl6kqwbUndGB/xBxHJlDKlL/NZKgi/3bQq+cbxBjh86d7eMkUjW
tHnIMtg/0whPhZtLAlnIDAGgFk4dXLK4OJmlRShJlN+QMCp15BnXBmxPvrO+Emqk
fKUIGYNE3M3rcVa4Cu4R/J3e18O7Z8DX6ut/4N8t8Zos4NO+azYNXtqJq/3HzsEV
IQ7Hu/xTgmuGHuEMzOkXgTCym9qx+QIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
CSqGSIb3DQEBCwUAA4ICAQBroyluUJyEYnO5rLg9lGwbTDX22w0x5OiWD1HDvojo
mdqKY8/bDe1URaJEthkmYL/2VB7+5HMoidf/XQPEjPEGItE2ECDzA3g7Sc9baMrr
VpBJoRCHgRxI9qPiMOL52ofYYU8x8Tv/r371xliADnZComXZ//0Fnhb0ghBtnNxK
552ftcGco+LVrc9MEXzI2va7cax9JV029O0ketoPGSrDw6T7CQkGfot9k6rgQIiQ
7jo9awcyI3As7PFCgSixZmPqzEh1B+V15X/crC+5RF8vBdWmxARw3LcQLXx6Ba+8
lSK94gQ+ynhpmWUTR95+8Hr62LsChuK2+inPSs5m4phw7YJPNFlEiEMQyIltNAoD
J/PYoodEdlKMZXVbI4WgElP2eFNzYiLycweIa034BalYAag3euzV/Nt5zTjb3rUh
vLVmb19Lm+lsnN58z6bJWpCz7fxic6nyhapGtV7hZk+KM9nyDFAfxxaktv7PaKVS
ENNA7vculZhN3CD08HTZnjaHA835luCUseeNvc0zFHjpGOxD5W+T5GhPE66gdzE9
IbxoRX8ftMmkj1l8JtRUNxQ1iXW0iexLUtPxiooqjFI6JaxDPYWZ2q/dfSmyg9w5
eYcvCabhJoaNBqQeboge3F5+fYYhMFF2HjE/SjT2jaP/2DsQDuJwRigibQNwB83F
NQ==
-----END CERTIFICATE-----"""
org_name = "modern-libre-dev-group"