apiVersion: v1
kind: ConfigMap
metadata:
  name: certificates
  namespace: dev
data:
  develop.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAxpnk9d0/IxA72O6sm+Y5Q0tQ6g3z6eGi6b4usaO5z6bp0xsT
    ob4fKXMsyDY/jhFkBEo413Ot49+dH5WwaCk0DtYJd4Gbm6DRRYxSnwexbJgxwpdJ
    +YpuuvLRy4XurZkt9iEZo6O01dYTq0o8rkcD3IfKwTxzzKwtJt9XtxKnc755T2+8
    RyPsWyT0+8CJpfTulYYUzvNXUpclZGG45OLtEUePPQ6arERSfGxUeJN2TK8hHS+K
    /Im0ILhQmsvc+3FtFLEIt4Depan0P17AsHegXeLE7WQDa3W6xa368ZAe6qVBYZnA
    qqAh1Xb/CP6DnFo6iN6oHBA17Q95R4CSHntgnwIDAQABAoIBAAWyHDLrm0DVvQU3
    syHR7V/Us1ztvC34iVI9fTFWmEtpLaACieYK85yBmnFo2VOM2XdAspNNDZLDCFjK
    qOT3aYyTYKogwJDVnTkVZoBRGX/GBodQYh5LyoWi8glfWC7PtkeD6p4a02KltuKy
    SJM8Tih9bH80d7+C9fFvA682qUz/HBVh+fYx4kiLd1EgfQwrmuyWRv8qCuiIR32Y
    3ZypfeLUNcMMbamEBAaPitnLbFE+CavmxUIOFk03DZ/uAaB1JXOVftiXdfDMCPD2
    ZClR0RQbb5z0lrNJ3bkUZXAsktzJZYoirz4epcfftUZt1pYxQ2q9wtNxvZhOFo4K
    Z2vum4ECgYEA5wJLKiygxo3T58VI+2JZoUtFNq1gsbcko6Iqvm8SlkPCJ5W1ZoWl
    1i3KPqIiKSwLPam/qzphlQqJBT6kW83GmyBL2Ah2UzjI4oik0kfdTkfoAzNC/jTi
    AdsSnM6lG78eqo0xZMRrQOnKCdd9u4AfqetYiA+qjmlpQaCnyBEvlO8CgYEA3BYU
    IlVu7LCgjVgHktXj0wt/RltNWvsUy+ZdpYEDgb0SrBkY0cKCP4r7999lBx6f3Asy
    dI+EoUUoETQw+mVYLDuqp8X44wtFUc4P+q0KOYytjY260xuAZSjKLluL3MmbN5y+
    +kTOd8rIxKgHdBWXJRsIbIVUBLNkwN2e9hsAz1ECgYAKxaCbptkYaSSoehqdHkjv
    rILdudf4cYHT34v+tU84kpBLKD/9N94zzo7PvN+668LabT/yzBYgzQz2oaUoYsAQ
    G8FtoXdjChLT/WsyIwe+zruS6qEFGZIwY/bKORiZ4p+bdFoJSN93d29kZhgG1kKj
    ucW3EoPxgBjYZpVsTuDZIQKBgQCThbUfQnbk7ovf0mbZNMfOWgGJDoAugOhyuEqD
    OpQ4LZ1LgFMTnzahEy9L+hEFEbED1PmQCfdUBkASMBK4dKACnkgIx3nJ7m8bo20w
    kTauVq6qmJrnEKMiq5HCOxjn+LczMr0Mknx27ZVfxGWimSpD8/fUjhZARGM/qA36
    VyVW0QKBgQCj4I7xmbEG0TjCb2ttJvxk+XeEt4nU6MUVOaeiGRRR05pMAc3Da030
    Rd0GsS/TNefqYLaUHmR70B/jps2EvmB0ipyNpaYP+fVUrEWJxOkEkYfxe7HLfD0p
    BliND7F3u+tk1MPA9tH7SEGFR+fmp5AGmHIthdxhqmXBGh4t8CBw3Q==
    -----END RSA PRIVATE KEY-----
