apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-dev
  namespace: dev
data:
  KUBERNETES_SERVICE: "true"
  RUST_LOG: debug
  RUST_BACKTRACE: "1"
  DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DBNAME}
  PG_USER: postgres
  PG_HOST: 172.24.4.114
  PG_PORT: 5432
  PG_DBNAME: modernlibre
  PG_POOL_MAX_SIZE: "20"

  CASSDOOR_ENDPOINT: "http://192.168.77.132:8000"
  CASSDOOR_CLIENT_ID: "95b443e3087000d6cf64"
  CASSDOOR_CLIENT_SECRET: "dcd89484d7956e5351ac18f5fd6bf6d593e937b1"
  CASSDOOR_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
    bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MTExMTEwMDMxNFoXDTQ0
    MTExMTEwMDMxNFowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
    bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDemlsKwiWDN2RL
    0gaoD7Z/Zg9M5CLj8dqFAv3xHwtXwjmSddLgEj/iHNQSN1Xk3AQHRqmyeIhXbrvx
    fGaUdyu+hxt5Un83PHPHm3qwaT1YQzuLCLA3dMp5cHHQUXKyGvcU2Y3HSsuYbuIB
    jL664pU8H5G/ldD+8x8D5DtONhOCxW+48uUrWMLGhL/m0a5fRqKDP2P98BNTACTd
    xfBGfTusu5duQJ0D9UkguyM6fyVdETUn9zRbwTirbICXgJGU1M1MBWBsEyeLX0Fs
    NhKlVjK43mdqwHKI9sMKr3BfyNP7axlceeglvWuv6CQaHcIt62/X5dQLQCtdp2VC
    L8kdUsKXkU/e18CeY6DxUcermzUZSv3HnwVYtklDofEww9SCNKiU7UrkEfVaq1T7
    S0vLNyvfY/t66RRhJ91Z4O81a7CWFwefBOQEAYBQtoWc+cFmj4KleDjsROQXM0QG
    MIFD6fS4GYPQpd0iqGrRQZUG26FK1occa3uIS0TbJuY37oP/oKZYpKXWgf7BHElV
    asmfw91ESNXhEnxVw9EOl2NSrKdCAQugw3Kh8SB9tF84UIP1bqcg7P0IxY7Fyvnv
    x4Q7A1ufoqb7QwMUyJdD2OFqhAVktecGpZ1+Q2BAT3BS+zORju/aM6YBcpwxNyN1
    DsDmoH4TNKKIvqSeN5ZkVKzEkUCWuQIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
    CSqGSIb3DQEBCwUAA4ICAQBLLxLC22Sm98Vfl0dtFZ2ZqNz9Exk7eg3rH+jsVeKV
    1qle46c0ci6EZ6/bMoDDrE8FJ1EXDbuVSwQ9ijzr6jO51K2ms7v5sqqsemsshDF6
    gXrIExp6siO+hqla5Ylacp9jXuRtHwsNkXiZuUZTHZ3b8QkG/sSfZWXnWwaLtHKs
    CJRlssvTQWz4xQQnomY9htaTaVdm6yce/sDGI4UASmk/5mZVE6SjtWbqg0RNp1/4
    IgH/lo6X5jVVWNsNZwEOFSl9arH0pqHjGNvFNJbfZ0woLjo5AcZOxinvUIu1ae4b
    c0QxbgBgNPLWsdkGgbnAONKHfmsQIVav/Tf2iPZic5EQ4bAGxjgSeSrIbonKtyad
    2Yq5y5zLeqPohSg9h3YvxOKfNAvw5CMmsSvD4dJsEerkVK9BN5twyCJyhf7EtyBK
    78YTCWtmgBxjxASshjfSwxgZywqVP4wArn4d5IA2pi69YXcM+FyzmmeK3qzfe5mK
    MKpMUsHIw4q1SzrttYktiEauhzLh7wcK2sPJ4zm0YDyT6mR/Md+N+5BraNvSsH28
    TSjFJPSKfyH5eBQumsRE/dCp3yvhq8DDAiHy//uWSdxp0B/KayX54Jz00mpLpcq4
    AC+FQXkQk0Sn74PC4OxtTX/AuJwn93Kh61ZESE0xIUMyjzJiXaH2J+m37A+x8pnM
    Rw==
    -----END CERTIFICATE-----
  CASSDOOR_ORG_NAME: "casbin"
  CASSDOOR_APP_NAME: ""