apiVersion: v1
kind: Service
metadata:
  name: libre-service
  namespace: dev
spec:
  selector:
    app: libre-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort